# Generated by Django 4.1.6 on 2023-02-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="events/default.png", upload_to="events"
            ),
        ),
    ]
